export const MENU_VIEW = "MENU_VIEW";
export const MENU_GO_TO = "MENU_GO_TO";
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";

export const CALENDAR_EVENTS_VIEW_ALL = "CALENDAR_EVENTS_VIEW_ALL";
export const CALENDAR_EVENT_ADD = "CALENDAR_EVENT_ADD";
export const CALENDAR_EVENT_MODIFY = "CALENDAR_EVENT_MODIFY";
export const CALENDAR_EVENT_DELETE = "CALENDAR_EVENT_DELETE";
export const CALENDAR_EVENT_VIEW = "CALENDAR_EVENT_VIEW";

